'use client'

// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { FC, PropsWithChildren } from 'react'
import { DndProvider } from 'react-dnd'
import { HTML5Backend } from 'react-dnd-html5-backend'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

interface RootLayoutType extends PropsWithChildren {}

const RootLayout: FC<RootLayoutType> = ({ children }) => (
  <html lang="en">
    <body suppressHydrationWarning className={inter.className}>
      <DndProvider backend={HTML5Backend}>{children}</DndProvider>
    </body>
  </html>
)

export default RootLayout

// export const metadata: Metadata = {
//   title: 'Travelboost',
//   description: 'Generated by create next app',
// }
